# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archius_schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61rchius_schema.proto\"\x15\n\x04\x46\x61to\x12\r\n\x05texto\x18\x01 \x01(\t\"\x1b\n\nSubdominio\x12\r\n\x05\x66\x61tos\x18\x01 \x03(\t\"\x82\x01\n\rTopicosAtivos\x12.\n\x08\x64ominios\x18\x01 \x03(\x0b\x32\x1c.TopicosAtivos.DominiosEntry\x1a\x41\n\rDominiosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.MapaSubdominios:\x02\x38\x01\"\x8a\x01\n\x0fMapaSubdominios\x12\x36\n\x0bsubdominios\x18\x01 \x03(\x0b\x32!.MapaSubdominios.SubdominiosEntry\x1a?\n\x10SubdominiosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.Subdominio:\x02\x38\x01\"M\n\x0f\x44\x65\x63isaoRevogada\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x18\n\x10revoked_in_chunk\x18\x03 \x01(\t\"M\n\x08MetaData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x1c\n\x14last_processed_chunk\x18\x02 \x01(\t\x12\x12\n\nupdated_at\x18\x03 \x01(\t\"}\n\rEstadoSistema\x12\x18\n\x05_meta\x18\x01 \x01(\x0b\x32\t.MetaData\x12%\n\ractive_topics\x18\x02 \x01(\x0b\x32\x0e.TopicosAtivos\x12+\n\x11revoked_decisions\x18\x03 \x03(\x0b\x32\x10.DecisaoRevogada\"U\n\rChunkContexto\x12\x16\n\x0e\x61rquivo_origem\x18\x01 \x01(\t\x12\x13\n\x0btexto_bruto\x18\x02 \x01(\t\x12\x17\n\x0findex_sequencia\x18\x03 \x01(\x05\"*\n\x12\x45xtracaoFidelidade\x12\x14\n\x0c\x66\x61tos_brutos\x18\x01 \x03(\t\"c\n\x12RelatorioAuditoria\x12\x10\n\x08\x61provado\x18\x01 \x01(\x08\x12\x19\n\x11motivo_reprovacao\x18\x02 \x01(\t\x12 \n\x18\x64\x61\x64os_faltantes_ou_erros\x18\x03 \x03(\t\"m\n\x12PropostaRoteamento\x12&\n\x0epatch_insercao\x18\x01 \x01(\x0b\x32\x0e.TopicosAtivos\x12/\n\x15proposicoes_revogacao\x18\x02 \x03(\x0b\x32\x10.DecisaoRevogadab\x06proto3')



_FATO = DESCRIPTOR.message_types_by_name['Fato']
_SUBDOMINIO = DESCRIPTOR.message_types_by_name['Subdominio']
_TOPICOSATIVOS = DESCRIPTOR.message_types_by_name['TopicosAtivos']
_TOPICOSATIVOS_DOMINIOSENTRY = _TOPICOSATIVOS.nested_types_by_name['DominiosEntry']
_MAPASUBDOMINIOS = DESCRIPTOR.message_types_by_name['MapaSubdominios']
_MAPASUBDOMINIOS_SUBDOMINIOSENTRY = _MAPASUBDOMINIOS.nested_types_by_name['SubdominiosEntry']
_DECISAOREVOGADA = DESCRIPTOR.message_types_by_name['DecisaoRevogada']
_METADATA = DESCRIPTOR.message_types_by_name['MetaData']
_ESTADOSISTEMA = DESCRIPTOR.message_types_by_name['EstadoSistema']
_CHUNKCONTEXTO = DESCRIPTOR.message_types_by_name['ChunkContexto']
_EXTRACAOFIDELIDADE = DESCRIPTOR.message_types_by_name['ExtracaoFidelidade']
_RELATORIOAUDITORIA = DESCRIPTOR.message_types_by_name['RelatorioAuditoria']
_PROPOSTAROTEAMENTO = DESCRIPTOR.message_types_by_name['PropostaRoteamento']
Fato = _reflection.GeneratedProtocolMessageType('Fato', (_message.Message,), {
  'DESCRIPTOR' : _FATO,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:Fato)
  })
_sym_db.RegisterMessage(Fato)

Subdominio = _reflection.GeneratedProtocolMessageType('Subdominio', (_message.Message,), {
  'DESCRIPTOR' : _SUBDOMINIO,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:Subdominio)
  })
_sym_db.RegisterMessage(Subdominio)

TopicosAtivos = _reflection.GeneratedProtocolMessageType('TopicosAtivos', (_message.Message,), {

  'DominiosEntry' : _reflection.GeneratedProtocolMessageType('DominiosEntry', (_message.Message,), {
    'DESCRIPTOR' : _TOPICOSATIVOS_DOMINIOSENTRY,
    '__module__' : 'archius_schema_pb2'
    # @@protoc_insertion_point(class_scope:TopicosAtivos.DominiosEntry)
    })
  ,
  'DESCRIPTOR' : _TOPICOSATIVOS,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:TopicosAtivos)
  })
_sym_db.RegisterMessage(TopicosAtivos)
_sym_db.RegisterMessage(TopicosAtivos.DominiosEntry)

MapaSubdominios = _reflection.GeneratedProtocolMessageType('MapaSubdominios', (_message.Message,), {

  'SubdominiosEntry' : _reflection.GeneratedProtocolMessageType('SubdominiosEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPASUBDOMINIOS_SUBDOMINIOSENTRY,
    '__module__' : 'archius_schema_pb2'
    # @@protoc_insertion_point(class_scope:MapaSubdominios.SubdominiosEntry)
    })
  ,
  'DESCRIPTOR' : _MAPASUBDOMINIOS,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:MapaSubdominios)
  })
_sym_db.RegisterMessage(MapaSubdominios)
_sym_db.RegisterMessage(MapaSubdominios.SubdominiosEntry)

DecisaoRevogada = _reflection.GeneratedProtocolMessageType('DecisaoRevogada', (_message.Message,), {
  'DESCRIPTOR' : _DECISAOREVOGADA,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:DecisaoRevogada)
  })
_sym_db.RegisterMessage(DecisaoRevogada)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:MetaData)
  })
_sym_db.RegisterMessage(MetaData)

EstadoSistema = _reflection.GeneratedProtocolMessageType('EstadoSistema', (_message.Message,), {
  'DESCRIPTOR' : _ESTADOSISTEMA,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:EstadoSistema)
  })
_sym_db.RegisterMessage(EstadoSistema)

ChunkContexto = _reflection.GeneratedProtocolMessageType('ChunkContexto', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKCONTEXTO,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:ChunkContexto)
  })
_sym_db.RegisterMessage(ChunkContexto)

ExtracaoFidelidade = _reflection.GeneratedProtocolMessageType('ExtracaoFidelidade', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACAOFIDELIDADE,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:ExtracaoFidelidade)
  })
_sym_db.RegisterMessage(ExtracaoFidelidade)

RelatorioAuditoria = _reflection.GeneratedProtocolMessageType('RelatorioAuditoria', (_message.Message,), {
  'DESCRIPTOR' : _RELATORIOAUDITORIA,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:RelatorioAuditoria)
  })
_sym_db.RegisterMessage(RelatorioAuditoria)

PropostaRoteamento = _reflection.GeneratedProtocolMessageType('PropostaRoteamento', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSTAROTEAMENTO,
  '__module__' : 'archius_schema_pb2'
  # @@protoc_insertion_point(class_scope:PropostaRoteamento)
  })
_sym_db.RegisterMessage(PropostaRoteamento)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPICOSATIVOS_DOMINIOSENTRY._options = None
  _TOPICOSATIVOS_DOMINIOSENTRY._serialized_options = b'8\001'
  _MAPASUBDOMINIOS_SUBDOMINIOSENTRY._options = None
  _MAPASUBDOMINIOS_SUBDOMINIOSENTRY._serialized_options = b'8\001'
  _FATO._serialized_start=24
  _FATO._serialized_end=45
  _SUBDOMINIO._serialized_start=47
  _SUBDOMINIO._serialized_end=74
  _TOPICOSATIVOS._serialized_start=77
  _TOPICOSATIVOS._serialized_end=207
  _TOPICOSATIVOS_DOMINIOSENTRY._serialized_start=142
  _TOPICOSATIVOS_DOMINIOSENTRY._serialized_end=207
  _MAPASUBDOMINIOS._serialized_start=210
  _MAPASUBDOMINIOS._serialized_end=348
  _MAPASUBDOMINIOS_SUBDOMINIOSENTRY._serialized_start=285
  _MAPASUBDOMINIOS_SUBDOMINIOSENTRY._serialized_end=348
  _DECISAOREVOGADA._serialized_start=350
  _DECISAOREVOGADA._serialized_end=427
  _METADATA._serialized_start=429
  _METADATA._serialized_end=506
  _ESTADOSISTEMA._serialized_start=508
  _ESTADOSISTEMA._serialized_end=633
  _CHUNKCONTEXTO._serialized_start=635
  _CHUNKCONTEXTO._serialized_end=720
  _EXTRACAOFIDELIDADE._serialized_start=722
  _EXTRACAOFIDELIDADE._serialized_end=764
  _RELATORIOAUDITORIA._serialized_start=766
  _RELATORIOAUDITORIA._serialized_end=865
  _PROPOSTAROTEAMENTO._serialized_start=867
  _PROPOSTAROTEAMENTO._serialized_end=976
# @@protoc_insertion_point(module_scope)
